version: '3.8'

services:

  web:
    restart: always
    container_name: web_rental
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
        - pgdb

  pgdb:
    container_name: pgdb_rental
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#  esearch:
#    container_name: search
#    image: elasticsearch:7.14.2
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#    ports:
#      - 9200:9200
#    healthcheck:
#      test: 'exit 0'