version: '3.8'

services:
  pgdb:
    container_name: pgdb_rental
    image: postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#pgadmin:
#  container_name: pgadmin4
#  image: dpage/pgadmin4
#  restart: always
#
#  environment:
#    PGADMIN_DEFAULT_EMAIL: admin@admin.com
#    PGADMIN_DEFAULT_PASSWORD: password
#    ports:
#      - '5050:80'

  esearch:
    container_name: search
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200